version: 2
jobs:
  build:
    docker:
    - image: singularitynet/platform-pipeline
    working_directory: /root/singnet/src/github.com/singnet/platform-pipeline
    environment:
      GOPATH: /root/singnet
      SINGNET_REPOS: /root/singnet/src/github.com/singnet
    steps:
    - run:
        name: Show parent project info
        command: |
          echo PARENT_PROJECT_REPONAME=$PARENT_PROJECT_REPONAME
          echo PARENT_BRANCH=$PARENT_BRANCH
          echo PARENT_BUILD_URL=$PARENT_BUILD_URL
    - run:
        name: Install tools
        command: |
          export PATH=$PATH:$GOPATH/bin
          mkdir $GOPATH/download
          cd $GOPATH/download
    - run:
        name: Clone token-contracts, platform-contracts, snet-cli & snet-daemon
        command: |
          cd $SINGNET_REPOS
          git clone https://github.com/singnet/token-contracts.git
          git clone https://github.com/singnet/platform-contracts.git
          git clone https://github.com/singnet/snet-cli.git
          git clone https://github.com/singnet/snet-daemon.git
    - restore_cache:
        keys:
          - dependency-cache-{{ checksum "../token-contracts/package.json" }}
          - dependency-cache-{{ checksum "../platform-contracts/package.json" }}
          - dependency-cache-{{ checksum "../snet-daemon/Gopkg*" }}
    - run:
        name: Build token-contracts
        command: |
          cd $SINGNET_REPOS/token-contracts
          npm install
          npm run-script compile
          npm run-script package-npm
    - run:
        name: Build platform-contracts
        command: |
          cd $SINGNET_REPOS/platform-contracts
          npm install ganache-cli@6.3.0
          # install token-contracts from local dir
          npm install $SINGNET_REPOS/token-contracts/build/npm-module
          npm install
          npm run-script compile
          npm run-script package-npm
    - run:
        name: Build snet-cli
        command: |
          cd $SINGNET_REPOS/snet-cli
          # install token-contracts and platform-contracts from local dir
          pushd blockchain/
          npm install $SINGNET_REPOS/token-contracts/build/npm-module
          npm install $SINGNET_REPOS/platform-contracts/build/npm-module
          popd
          ./packages/snet_cli/scripts/blockchain install
          pip3 install -e ./packages/snet_cli
    - run:
        name: Build snet-daemon
        command: |
          export PATH=$PATH:$GOPATH/bin
          cd $SINGNET_REPOS/snet-daemon
          # install token-contracts and platform-contracts from local dir
          pushd resources/blockchain
          npm install $SINGNET_REPOS/token-contracts/build/npm-module
          npm install $SINGNET_REPOS/platform-contracts/build/npm-module
          popd
          ./scripts/install
          ./scripts/build linux amd64 `git describe --tag`
          ln -s $SINGNET_REPOS/snet-daemon/build/snetd-linux-amd64 /usr/local/bin/snetd
    - run:
        name: Build example_service
        command: |
          export PATH=$PATH:$GOPATH/bin
          cd $SINGNET_REPOS
          git clone https://github.com/singnet/example-service.git
    - checkout
    - run:
        name: Run integration tests
        command: |
          export PATH=$PATH:$GOPATH/bin
          export IPFS_PATH=$GOPATH/ipfs
          mkdir $GOPATH/log
          go get github.com/DATA-DOG/godog/cmd/godog
          go get github.com/ethereum/go-ethereum/common
          godog
    - save_cache:
        key: dependency-cache-{{ checksum "../token-contracts/package.json" }}
        paths:
          - ../token-contracts/node_modules
    - save_cache:
        key: dependency-cache-{{ checksum "../platform-contracts/package.json" }}
        paths:
          - ../platform-contracts/node_modules
    - save_cache:
        key: dependency-cache-{{ checksum "../snet-daemon/Gopkg*" }}
        paths:
          - ../../../../pkg
